### ISSUE TITLE
[BUG] - Rasa Spelling PLAYGROUND

### ISSUE THREAD

**Issue by rmiaouh** [RasaHQ/rasalit#37]
Hi guys & @koaning. Your work is amazing.

I have an issue with the **Rasa Spelling PLAYGROUND** 

![image](https://user-images.githubusercontent.com/43033520/107940084-f82e8b00-6f87-11eb-8619-0171e2761817.png)

My model trained with : Rasa V2.1.3
RasaLit : V0.1.2
![image](https://user-images.githubusercontent.com/43033520/107940184-201dee80-6f88-11eb-8d61-040535d46c72.png)

```
File "/home/robin/askMona_Projets/1_Projet_NomDeLieux/ArDf/Divers_Tests/TEST_RASA/env/lib/python3.6/site-packages/streamlit/script_runner.py", line 332, in _run_script
    exec(code, module.__dict__)
File "/home/robin/askMona_Projets/1_Projet_NomDeLieux/ArDf/Divers_Tests/TEST_RASA/env/lib/python3.6/site-packages/rasalit/apps/spelling/app.py", line 50, in <module>
    preds = clf.predict_proba(augs)
File "/home/robin/askMona_Projets/1_Projet_NomDeLieux/ArDf/Divers_Tests/TEST_RASA/env/lib/python3.6/site-packages/rasalit/apps/spelling/classifier.py", line 93, in predict_proba
    result.append([ranking_dict[n] for n in self.class_names_])
File "/home/robin/askMona_Projets/1_Projet_NomDeLieux/ArDf/Divers_Tests/TEST_RASA/env/lib/python3.6/site-packages/rasalit/apps/spelling/classifier.py", line 93, in <listcomp>
    result.append([ranking_dict[n] for n in self.class_names_])
```

_________________________________

KeyError: 'smalltalk residence'
Looks like it doesn't like how I called my Intent ?

**Comment by koaning** [comment]
I have a feeling that this might be related to your config.yml setting. Did you have a max-ranking set in DIET by any chance?

**Comment by rmiaouh** [comment]
I will send you my Metadata.json. I dont think i have a max-ranking ?

[metadata.txt](https://github.com/RasaHQ/rasalit/files/5982453/metadata.txt)

**Comment by koaning** [comment]
Ah yeah, I think I've found the issue. Your DIET classifier doesn't predict *all* possible values because of this setting;

```
"ranking_length": 10,
```

It's something that I need to fix on my end though. So it's added to the TODO pile for this week. Thanks for reporting! 

Will ping here one there's a fix.

**Comment by rmiaouh** [comment]
Oh thank you for all. Now I understand all the logic behind this bug. 
I train models with 90 intents. Can this parameter impact the output performance of the model? Or this parameter only impacts the number of intents it displays ?

**Comment by koaning** [comment]
I'm not 100% sure yet, but I'll try to investigate this.

**Comment by koaning** [comment]
I've just pushed a fix. Today I learned that Rasa pipelines don't expose all the intent confidence scores on prediction. Only if you configure DIET to do so. The fix turned out to be simple and we're now also robust against the changes made to the confidence change. 

In case you haven't seen the [announcement](https://www.youtube.com/watch?v=0cC5Cb3RuIo&t=1s&ab_channel=Rasa) yet.

**Comment by rmiaouh** [comment]
`I've just pushed a PR with a fix, once tests are green it will be merged. Could you let me know if it works?`
@koaning It's perfect ! Ty for all 
![image](https://user-images.githubusercontent.com/43033520/108091988-871ccf80-707c-11eb-9c84-0394e15d59d3.png)


May I ask you a last question ?
I currently have a problem with the DIET entity detection. 
For exemple : if I train the entity "**Livre**" _(means "book" in french)_ and I call the word "**Live**", the Diet entity detector will think it's the world "Livre". 
![image](https://user-images.githubusercontent.com/43033520/108093061-9e0ff180-707d-11eb-9cd1-d2354cb740a5.png)
And I think it's because of the CountVectors in my config : 
  - name: CountVectorsFeaturizer
    analyzer: "char_wb"
    min_ngram: 1
    max_ngram: 4

But from what I know the CountVectors is essential for better performance.
Do you have a strategy to avoid this problem?

![image](https://user-images.githubusercontent.com/43033520/108094474-1f1bb880-707f-11eb-9660-d9d44e9dc9c3.png)

Ty for all, I will watch the video :).

**Comment by koaning** [comment]
What entities are you trying to detect? Maybe a RegexEntityExtractor works better here.
