### ISSUE TITLE
missing whatlies dependency

### ISSUE THREAD

**Issue by Btibert3** [RasaHQ/rasalit#45]
**Expected**: In a clean virtual environment, install rasalit via instructions from README, and once installed, I could run `python -m rasalit nlu-cluster` 

**Actual**: Streamlit runs as expected, but the app shows the error below

![image](https://user-images.githubusercontent.com/203343/110241448-d0936880-7f1e-11eb-83ad-6fd29024d80e.png)

**Comment by sara-tagger** [comment]
Thanks for raising this issue, @koaning will get back to you about it soon✨

###### Please also check out the [docs](https://rasa.com/docs/) and the [forum](https://forum.rasa.com/) in case your issue was raised there too 🤗

**Comment by koaning** [comment]
Mhm... that should not happen. Will investigate! 

I'm on holiday now, but you can expect a fix around Friday.

**Comment by koaning** [comment]
Just to confirm though, after installing `pip install whatlies` it does work?

**Comment by Btibert3** [comment]
It does, as that lead me to #46

**Comment by koaning** [comment]
In this case I'm leaning towards adding something in the docs to make this clear. The other apps do not require `whatlies`.
