### ISSUE TITLE
Missing Rasa logo

### ISSUE THREAD

**Issue by Btibert3** [RasaHQ/rasalit#46]
**Expected**:  I should be able to install into a clean virtual environment and run `python -m rasalit nlu-cluster` and see the streamlit app

**Actual**: I was able to load the streamlit app (after pip installing whatlies into the same env), but I got the following error:

![image](https://user-images.githubusercontent.com/203343/110241587-8e1e5b80-7f1f-11eb-88fa-59abd69bb435.png)

**Comment by sara-tagger** [comment]
Thanks for the issue, @kalkbrennerei will get back to you about it soon!

###### You may find help in the [docs](https://rasa.com/docs/) and the [forum,](https://forum.rasa.com/) too 🤗

**Comment by koaning** [comment]
Urgh. That's awkward. I'm on holiday now, but you can expect a fix around Friday.

**Comment by koaning** [comment]
One thing: for future reference. Could you post the text along with the screenshot? It's much easier to copy/paste and search in text.

**Comment by Btibert3** [comment]
Absolutely, oversight there.

**Comment by koaning** [comment]
I've not been able to reproduce this issue, just to check @Btibert3 are you sure it wasn't a temporary internet hiccup?

**Comment by koaning** [comment]
Strange. I have been able to reproduce now. Might be a github cookie thing? I'll remove the image for now.

**Comment by koaning** [comment]
Link to PR: https://github.com/RasaHQ/rasalit/pull/48
